[package]
name = "tattle"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.8"
dotenv = "0.15.0"
futures-util = "0.3.31"
http-body-util = "0.1.3"
memory-serve = "1.2.2"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "rt", "signal"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[dev-dependencies]
reqwest = "0.13.1"
tokio = { version = "1.49.0", features = ["process", "time"] }
tower = { version = "0.5.3", features = ["util"] }

[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.30.1", features = ["process", "signal"] }

[profile.release]
panic = "abort"
lto = true
