[package]
name = "klatsch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
async-sqlite = "0.5.6"
async-stream = "0.3.6"
axum = { version = "0.8.8", features = ["macros"] }
dotenv = "0.15.0"
futures-util = "0.3.32"
http-body-util = "0.1.3"
memory-serve = "2.0.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "rt", "signal"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { version = "1.21.0", features = ["serde"] }

[dev-dependencies]
double-trait = { version = "0.2.9", features = ["stream"] }
reqwest = "0.13.2"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["process", "time"] }
tokio-test = "0.4.5"
tower = { version = "0.5.3", features = ["util"] }
uuid = { version = "1.21.0", features = ["serde", "v7"] }

[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.31.1", features = ["process", "signal"] }

[profile.release]
panic = "abort"
lto = true
