[package]
name = "tattle"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.8"
dotenv = "0.15.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "rt", "signal"] }

[dev-dependencies]
reqwest = "0.13.1"
tokio = { version = "1.49.0", features = ["process", "time"] }

[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.30.1", features = ["process", "signal"] }

[target.'cfg(windows)'.dev-dependencies]
# To send Ctrl-C event to child process on Windows
windows = { version = "0.62.2", features = ["Win32_System_Console"] }

[profile.release]
panic = "abort"
lto = true
